### ISSUE TITLE
it's a wrong

### ISSUE THREAD

**Issue by hahahachinazhang** [xStaBUx/Omaloon-public#35]
![%{BL UO$54@~8_1@F_)VWLN](https://user-images.githubusercontent.com/97344802/227769078-df01cdb5-017a-4918-9d6c-a32aefcc9fcc.png)

**Comment by xStaBUx** [comment]
Crash log file plz

**Comment by xStaBUx** [comment]
@hahahachinazhang 
what exactly did you do?
How did it happen?
Are you using the latest release of Mindustry and Omaloon?
Provide a crash log file

**Comment by xStaBUx** [comment]
no problem provided
